@host=http://localhost:3001

### Health check
GET {{host}}/health_check

### List available report months
GET {{host}}/api/reports/available-months

### Request report generation
POST {{host}}/api/reports/generate
Content-Type: application/json

{
  "year": 2025,
  "month": 4
}

### Get a monthly report
GET {{host}}/api/reports/monthly/2025/4